# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: |
        ant
        java -cp april.jar april.tag.TagToC april.tag.TagStandard41h7
        cat scripts/copyright.txt > ../apriltags/TagStandard41h7.c
        cat TagStandard41h7.c >> ../apriltags/TagStandard41h7.c

        cat scripts/copyright.txt > ../apriltags/TagStandard41h7.h
        cat TagStandard41h7.h >> ../apriltags/TagStandard41h7.h

#java -cp april.jar april.tag.GenerateTags april.tag.TagStandard41h7

#java -cp april.jar april.tag.TagFamilyGenerator standard_9 7
